package com.project.focs.asymmetric;

import javax.xml.bind.DatatypeConverter;
import java.security.KeyPair;
import static org.junit.jupiter.api.Assertions.*;

class AsymmetricEncryptionUtilsTest {
    @Test
    void generateRSAKeyPair() throws Exception {
        KeyPair kp = AsymmetricEncryptionUtils.generateRSAKeyPair();
        assertNotNull(kp);

        System.out.println("KEY PAIR GENERATED BY ASYMMETRIC ENCRYPTION: \n");
        System.out.println("Private Key: " + DatatypeConverter.printHexBinary(kp.getPrivate().getEncoded()));
        System.out.println("Private Key: " + DatatypeConverter.printHexBinary(kp.getPublic().getEncoded()));
    }

}